name: Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # TODO

  zip-src:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true
    needs: test
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Zip src -> manageur.zip
      run: |
        zip -r manageur.zip src
        mv manageur.zip $GITHUB_WORKSPACE/
    
    - name: Upload manageur.zip
      uses: actions/upload-artifact@v2
      with:
        name: src-zip
        path: $GITHUB_WORKSPACE/manageur.zip
