name: Pipeline

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

  build-and-zip:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Zip src -> manageur.zip
      run: |
        zip -r manageur.zip src
        mv src.zip $GITHUB_WORKSPACE/
    
    - name: Upload manageur.zip
      uses: actions/upload-artifact@v2
      with:
        name: src-zip
        path: $GITHUB_WORKSPACE/src.zip
