name: Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Run tests
      run: |
        # Add your test commands here
        echo "Running tests"

  build-and-zip:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.event.head_commit.message == 'Merge pull request*'
    needs: test
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Zip src -> manageur.zip
      run: |
        zip -r manageur.zip src
        mv manageur.zip $GITHUB_WORKSPACE/
    
    - name: Upload manageur.zip
      uses: actions/upload-artifact@v2
      with:
        name: src-zip
        path: $GITHUB_WORKSPACE/manageur.zip
